---
title: "JK NP"
author: "Natnael Eshetu, Phoebe Ng, Kyle Simpson, Joe Zhang"
date: "5/28/2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(formattable)
library(plotly)
library(knitr)
library(usmap)
library(shiny)
library(dplyr)
library(ggplot2)
library(plotly)
library(readxl)
library(plotly)
library(usmap)
library(choroplethr)
library(choroplethrMaps)
 source("analysis/sociobesity.R")
# source("./analysis/age_insecurity.R")
source("analysis/healthy_wash.R")
```

## Introduction


-----

## Is socioeconomic status linked to adult obesity rates?
The first way we will look at food insecurity data is by looking at socioeconomic status and healthy lifestyles, by asking the question: "Is adult obesity rate linked to socioeconomic status?". We will analyze the strength of the correlation between the poverty rates and adult obesity rates, along with the correlation between median household income and adult obesity rates at both the county and state level, to see if there is any real connection between socioeconomic status and adult obesity rates. 

The first way we look at the relationship is by calculating the correlation coefficient between adult poverty rates, and obesity rates at the state level. Which reveals a coefficient of `r state_level_correlation`, which proves to be a moderate positive correlation, which means that there is some relationship between poverty and obesity at the state level. 

``` {r obesity1, echo=FALSE}
state_level_correlation_plot
```

The second way we look at the relationship is by focusing on the correlation at the county level. The correlation coefficient of `r county_level_correlation`, is still moderately positive, however it is clear to see that there are certain trends and relationships. Such as there are no counties with an adult poverty rate less than 10% with a obesity rate greater than 40%, and there are no counties with an adult poverty rate greater than 40% with an obesity rate less than 30%

``` {r obesity2, echo=FALSE}
county_level_correlation_plot
```

The third way we look at the relationship is by comparing both sides of the poverty spectrum. We look at the top ten counties with the highest and lowest poverty rates, along with their obesity rates. Both sides of the spectrum show clear trends in obesity, and difference in healthy lifestyles.
``` {r obesity3, echo=FALSE}
kable(highest_poverty, col.names = c("State", "County", "Poverty Rate", "Adult Obesity Rate"))
```
``` {r obesity4, echo=FALSE}
kable(lowest_poverty, col.names = c("State", "County", "Poverty Rate", "Adult Obesity Rate"))
```

Another way to look at the link between socio economic status and obesity is through the lens of household income. The correlation between median household income and obesity is moderately strong with a coefficient of `r income_correlation`, showing that the lower the income the greater the rates of obesity, and vice versa. 

``` {r obesity5, echo=FALSE}
income_correlation_plot
```

Finally we look at the data through an interactive map of all the US counties that provided data for analysis. One map contains the counties and their adult obesity rates, while the second map contains displays counties and a variable socioeconomic factor. This visualization helps show the trends in the different regions of the united states, parts of each state and how the obesity rates correlate to the various socioeconomic rates.
``` {r obesity6, echo=FALSE}
selectInput("Economic_Factor", "Chose a metric",
            choices=c("Med_HH_Income_2015 ", "Pov_Rate_2015", "Child_Pov_Rate_2015", "Percent_Of_Obese_Adults"),
            selected="Pov_Rate_2015")
renderPlotly({
  obese_comp_plot <- plot_usmap(data=work_data, values=input$Economic_Factor, regions="counties",
                       include=work_data$fips, aes(tooltip=county)) +
            theme(legend.position = "none",
                  axis.title.x = element_blank(),
                  axis.ticks.x = element_blank(),
                  axis.text.x = element_blank(),
                  axis.title.y = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.text.y = element_blank())+
    scale_fill_continuous(low = "blue", high = "yellow", guide = FALSE)
  ggplotly(obese_comp_plot)
})
```

After looking at this data in various ways, there is no one socio economic factor that we can use as the major cause of obesity. However, we can acknowledge the boundaries that people of lower socioeconomic status/economic status face when it comes to staying healthy. Poorer families and people often face the problems of choosing high-fat foods dense with energy due to their affordability, living in food deserts where healthy foods are hard to find, economic insecurity, activities being unavailable or unaffordable, which all can contribute to obesity. Which means that there is definitely some link, however with all types of cofounding variables from location, climate, safety, and many other things that vary from area to area its hard to say what exactly is the cause of obesity across the united states, or even at the county level.  

-----

## Does food insecurity vary by age?


-----

## In Washington, what counties have the least amount of access to healthy food?
The final way we will dissect food insecurity data is in the state of Washington.  This section will be guided by the question: "In Washington, what counties have the least amount of access to healthy food?".  We will analyze this question by comparing the ratios of fast food to full service reseaurants in each county, and by comparing the number of people served by farmers markets that accept SNAP/WIC/WICCASH/SFMNP vouchers in each county to comparatively assess the access to healthy foods per county.

Beginning with comparing the ratio of fast food restaurants to full service (F.F. / F.S.) to find the counties with the least access to healthy foods (i.e. the greatest proportion of fast food options to full service options), we can compute and sort by counties with the greatest proportion values.  The table below reports the top 5 counties in Washington with the least access to healthy foods based on fast food to full service restaurant proportion:

``` {r healthy1, echo=FALSE}
kable(plot_data[order(plot_data$fast_food, decreasing = TRUE),c("county", "fast_food")][1:5,], row.names = FALSE,
      col.names=c("County", "Fast Food to Full Service Proportion"))
```

The second way we will analyze the question is by comparing the number of people served by farmers markets that accept SNAP, WIC, WICCASH, and SFMNP - a series of food support programs that help families pay for food necessities.  We can again compute and sort by counties with the greatest number of people served by one farmer's market to assess the amount of healthy options available to low-income residents.  The tables below report the top 5 counties in Washington with the least access to healthy foods based on the highest proportion of county residents to markets accepting the food support program (note that some values will be equal to the population size if there aren't any markets accepting the type of food support program):

``` {r healthy2, echo=FALSE}
kable(plot_data[order(plot_data$snap, decreasing = TRUE),c("county", "snap")][1:5,], row.names = FALSE,
      col.names = c("County", "Number of Residents per Market accepting SNAP"))
```
``` {r healthy3, echo=FALSE}
kable(plot_data[order(plot_data$wic, decreasing = TRUE),c("county", "wic")][1:5,], row.names = FALSE,
      col.names = c("County", "Number of Residents per Market accepting WIC"))
```
``` {r healthy4, echo=FALSE}
kable(plot_data[order(plot_data$wiccash, decreasing = TRUE),c("county", "wiccash")][1:5,], row.names = FALSE,
      col.names = c("County", "Number of Residents per Market accepting WIC CASH"))
```
``` {r healthy5, echo=FALSE}
kable(plot_data[order(plot_data$sfmnp, decreasing = TRUE),c("county", "sfmnp")][1:5,], row.names = FALSE,
      col.names = c("County", "Number of Residents per Market accepting SFMNP"))
```

From each of these tables we see some counties that frequently appear as counties with low access to healthy foods (as measured by these metrics).  **Benton County**, **Spokane County**, **Grant County**, and **Snohomish County** are all in at least three of these tables, indicating that these may be high risk areas for unhealthy tendencies and health risks.

The final way we will visualize our data is through an interactive county-level map.  In the map below, you can change the metric of evaluation using the dropdown and hover over individual counties to see the name of the county and the metric data in that county.

``` {r healthy6, echo=FALSE}
selectInput("metric", "Chose a metric",
            choices=c("fast_food", "snap", "wic", "wiccash", "sfmnp"),
            selected="fast_food")

renderPlotly({
  plot <- plot_usmap(data=plot_data, values=input$metric, regions="counties",
                       include=fast_v_full$fips, aes(tooltip=county)) +
            theme(legend.position = "none",
                  axis.title.x = element_blank(),
                  axis.ticks.x = element_blank(),
                  axis.text.x = element_blank(),
                  axis.title.y = element_blank(),
                  axis.ticks.y = element_blank(),
                  axis.text.y = element_blank())
  ggplotly(plot)
})
```

-----

## Conclusions




```{r blockone, echo=FALSE}
# ggplotly(plotname)
```


``` {r blocktwo, echo=FALSE}
# kable(tablename)
```




